// Generated by gencpp from file collision_checker/CheckerResponse.msg
// DO NOT EDIT!


#ifndef COLLISION_CHECKER_MESSAGE_CHECKERRESPONSE_H
#define COLLISION_CHECKER_MESSAGE_CHECKERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <collision_checker/CollisionIDs.h>

namespace collision_checker
{
template <class ContainerAllocator>
struct CheckerResponse_
{
  typedef CheckerResponse_<ContainerAllocator> Type;

  CheckerResponse_()
    : ids()  {
    }
  CheckerResponse_(const ContainerAllocator& _alloc)
    : ids(_alloc)  {
  (void)_alloc;
    }



   typedef  ::collision_checker::CollisionIDs_<ContainerAllocator>  _ids_type;
  _ids_type ids;




  typedef boost::shared_ptr< ::collision_checker::CheckerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collision_checker::CheckerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckerResponse_

typedef ::collision_checker::CheckerResponse_<std::allocator<void> > CheckerResponse;

typedef boost::shared_ptr< ::collision_checker::CheckerResponse > CheckerResponsePtr;
typedef boost::shared_ptr< ::collision_checker::CheckerResponse const> CheckerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collision_checker::CheckerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collision_checker::CheckerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace collision_checker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'collision_checker': ['/home/puneet/foxconnmultiagent/catkin_ws/src/collision_checker/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::collision_checker::CheckerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collision_checker::CheckerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_checker::CheckerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_checker::CheckerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_checker::CheckerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_checker::CheckerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collision_checker::CheckerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bcc07d248949c25d6230c96a8ef5699";
  }

  static const char* value(const ::collision_checker::CheckerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bcc07d248949c25ULL;
  static const uint64_t static_value2 = 0xd6230c96a8ef5699ULL;
};

template<class ContainerAllocator>
struct DataType< ::collision_checker::CheckerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collision_checker/CheckerResponse";
  }

  static const char* value(const ::collision_checker::CheckerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collision_checker::CheckerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CollisionIDs ids\n\
\n\
================================================================================\n\
MSG: collision_checker/CollisionIDs\n\
int8[] colAgents\n\
";
  }

  static const char* value(const ::collision_checker::CheckerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collision_checker::CheckerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collision_checker::CheckerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collision_checker::CheckerResponse_<ContainerAllocator>& v)
  {
    s << indent << "ids: ";
    s << std::endl;
    Printer< ::collision_checker::CollisionIDs_<ContainerAllocator> >::stream(s, indent + "  ", v.ids);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLISION_CHECKER_MESSAGE_CHECKERRESPONSE_H
