// Generated by gencpp from file collision_checker/CheckerRequest.msg
// DO NOT EDIT!


#ifndef COLLISION_CHECKER_MESSAGE_CHECKERREQUEST_H
#define COLLISION_CHECKER_MESSAGE_CHECKERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace collision_checker
{
template <class ContainerAllocator>
struct CheckerRequest_
{
  typedef CheckerRequest_<ContainerAllocator> Type;

  CheckerRequest_()
    {
    }
  CheckerRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::collision_checker::CheckerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collision_checker::CheckerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckerRequest_

typedef ::collision_checker::CheckerRequest_<std::allocator<void> > CheckerRequest;

typedef boost::shared_ptr< ::collision_checker::CheckerRequest > CheckerRequestPtr;
typedef boost::shared_ptr< ::collision_checker::CheckerRequest const> CheckerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collision_checker::CheckerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collision_checker::CheckerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace collision_checker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'collision_checker': ['/home/puneet/foxconnmultiagent/catkin_ws/src/collision_checker/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::collision_checker::CheckerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collision_checker::CheckerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_checker::CheckerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_checker::CheckerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_checker::CheckerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_checker::CheckerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collision_checker::CheckerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::collision_checker::CheckerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::collision_checker::CheckerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collision_checker/CheckerRequest";
  }

  static const char* value(const ::collision_checker::CheckerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collision_checker::CheckerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::collision_checker::CheckerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collision_checker::CheckerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collision_checker::CheckerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::collision_checker::CheckerRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COLLISION_CHECKER_MESSAGE_CHECKERREQUEST_H
