// Generated by gencpp from file collision_checker/Checker.msg
// DO NOT EDIT!


#ifndef COLLISION_CHECKER_MESSAGE_CHECKER_H
#define COLLISION_CHECKER_MESSAGE_CHECKER_H

#include <ros/service_traits.h>


#include <collision_checker/CheckerRequest.h>
#include <collision_checker/CheckerResponse.h>


namespace collision_checker
{

struct Checker
{

typedef CheckerRequest Request;
typedef CheckerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Checker
} // namespace collision_checker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::collision_checker::Checker > {
  static const char* value()
  {
    return "9bcc07d248949c25d6230c96a8ef5699";
  }

  static const char* value(const ::collision_checker::Checker&) { return value(); }
};

template<>
struct DataType< ::collision_checker::Checker > {
  static const char* value()
  {
    return "collision_checker/Checker";
  }

  static const char* value(const ::collision_checker::Checker&) { return value(); }
};


// service_traits::MD5Sum< ::collision_checker::CheckerRequest> should match 
// service_traits::MD5Sum< ::collision_checker::Checker > 
template<>
struct MD5Sum< ::collision_checker::CheckerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::collision_checker::Checker >::value();
  }
  static const char* value(const ::collision_checker::CheckerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::collision_checker::CheckerRequest> should match 
// service_traits::DataType< ::collision_checker::Checker > 
template<>
struct DataType< ::collision_checker::CheckerRequest>
{
  static const char* value()
  {
    return DataType< ::collision_checker::Checker >::value();
  }
  static const char* value(const ::collision_checker::CheckerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::collision_checker::CheckerResponse> should match 
// service_traits::MD5Sum< ::collision_checker::Checker > 
template<>
struct MD5Sum< ::collision_checker::CheckerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::collision_checker::Checker >::value();
  }
  static const char* value(const ::collision_checker::CheckerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::collision_checker::CheckerResponse> should match 
// service_traits::DataType< ::collision_checker::Checker > 
template<>
struct DataType< ::collision_checker::CheckerResponse>
{
  static const char* value()
  {
    return DataType< ::collision_checker::Checker >::value();
  }
  static const char* value(const ::collision_checker::CheckerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLLISION_CHECKER_MESSAGE_CHECKER_H
