// Generated by gencpp from file collision_checker/CollisionIDs.msg
// DO NOT EDIT!


#ifndef COLLISION_CHECKER_MESSAGE_COLLISIONIDS_H
#define COLLISION_CHECKER_MESSAGE_COLLISIONIDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace collision_checker
{
template <class ContainerAllocator>
struct CollisionIDs_
{
  typedef CollisionIDs_<ContainerAllocator> Type;

  CollisionIDs_()
    : colAgents()  {
    }
  CollisionIDs_(const ContainerAllocator& _alloc)
    : colAgents(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _colAgents_type;
  _colAgents_type colAgents;




  typedef boost::shared_ptr< ::collision_checker::CollisionIDs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collision_checker::CollisionIDs_<ContainerAllocator> const> ConstPtr;

}; // struct CollisionIDs_

typedef ::collision_checker::CollisionIDs_<std::allocator<void> > CollisionIDs;

typedef boost::shared_ptr< ::collision_checker::CollisionIDs > CollisionIDsPtr;
typedef boost::shared_ptr< ::collision_checker::CollisionIDs const> CollisionIDsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collision_checker::CollisionIDs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collision_checker::CollisionIDs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace collision_checker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'collision_checker': ['/home/puneet/foxconnmultiagent/catkin_ws/src/collision_checker/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::collision_checker::CollisionIDs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collision_checker::CollisionIDs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_checker::CollisionIDs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collision_checker::CollisionIDs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_checker::CollisionIDs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collision_checker::CollisionIDs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collision_checker::CollisionIDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09c176dbe4cfa163d0f04c6e3f2169c8";
  }

  static const char* value(const ::collision_checker::CollisionIDs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09c176dbe4cfa163ULL;
  static const uint64_t static_value2 = 0xd0f04c6e3f2169c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::collision_checker::CollisionIDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collision_checker/CollisionIDs";
  }

  static const char* value(const ::collision_checker::CollisionIDs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collision_checker::CollisionIDs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] colAgents\n\
";
  }

  static const char* value(const ::collision_checker::CollisionIDs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collision_checker::CollisionIDs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.colAgents);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollisionIDs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collision_checker::CollisionIDs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collision_checker::CollisionIDs_<ContainerAllocator>& v)
  {
    s << indent << "colAgents[]" << std::endl;
    for (size_t i = 0; i < v.colAgents.size(); ++i)
    {
      s << indent << "  colAgents[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.colAgents[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLISION_CHECKER_MESSAGE_COLLISIONIDS_H
