// Generated by gencpp from file mstar/PlanPathResponse.msg
// DO NOT EDIT!


#ifndef MSTAR_MESSAGE_PLANPATHRESPONSE_H
#define MSTAR_MESSAGE_PLANPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mstar/Belief.h>

namespace mstar
{
template <class ContainerAllocator>
struct PlanPathResponse_
{
  typedef PlanPathResponse_<ContainerAllocator> Type;

  PlanPathResponse_()
    : paths()  {
    }
  PlanPathResponse_(const ContainerAllocator& _alloc)
    : paths(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mstar::Belief_<ContainerAllocator>  _paths_type;
  _paths_type paths;




  typedef boost::shared_ptr< ::mstar::PlanPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mstar::PlanPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanPathResponse_

typedef ::mstar::PlanPathResponse_<std::allocator<void> > PlanPathResponse;

typedef boost::shared_ptr< ::mstar::PlanPathResponse > PlanPathResponsePtr;
typedef boost::shared_ptr< ::mstar::PlanPathResponse const> PlanPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mstar::PlanPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mstar::PlanPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mstar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mstar': ['/home/puneet/foxconnmultiagent/catkin_ws/src/mstar/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mstar::PlanPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mstar::PlanPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mstar::PlanPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mstar::PlanPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mstar::PlanPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mstar::PlanPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mstar::PlanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "391ecf82d668e8209e91e9d40c9adfc0";
  }

  static const char* value(const ::mstar::PlanPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x391ecf82d668e820ULL;
  static const uint64_t static_value2 = 0x9e91e9d40c9adfc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mstar::PlanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mstar/PlanPathResponse";
  }

  static const char* value(const ::mstar::PlanPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mstar::PlanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Belief paths\n\
\n\
================================================================================\n\
MSG: mstar/Belief\n\
Path2D[] belief\n\
\n\
================================================================================\n\
MSG: mstar/Path2D\n\
int8 id\n\
int32 timestamp\n\
Pose2D[] poses\n\
\n\
================================================================================\n\
MSG: mstar/Pose2D\n\
float32 x\n\
float32 y\n\
float32 yaw\n\
int8 timeStamp\n\
";
  }

  static const char* value(const ::mstar::PlanPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mstar::PlanPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mstar::PlanPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mstar::PlanPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "paths: ";
    s << std::endl;
    Printer< ::mstar::Belief_<ContainerAllocator> >::stream(s, indent + "  ", v.paths);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSTAR_MESSAGE_PLANPATHRESPONSE_H
