// Generated by gencpp from file mstar/Pose2DList.msg
// DO NOT EDIT!


#ifndef MSTAR_MESSAGE_POSE2DLIST_H
#define MSTAR_MESSAGE_POSE2DLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mstar/Pose2D.h>

namespace mstar
{
template <class ContainerAllocator>
struct Pose2DList_
{
  typedef Pose2DList_<ContainerAllocator> Type;

  Pose2DList_()
    : poses()  {
    }
  Pose2DList_(const ContainerAllocator& _alloc)
    : poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mstar::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mstar::Pose2D_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;




  typedef boost::shared_ptr< ::mstar::Pose2DList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mstar::Pose2DList_<ContainerAllocator> const> ConstPtr;

}; // struct Pose2DList_

typedef ::mstar::Pose2DList_<std::allocator<void> > Pose2DList;

typedef boost::shared_ptr< ::mstar::Pose2DList > Pose2DListPtr;
typedef boost::shared_ptr< ::mstar::Pose2DList const> Pose2DListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mstar::Pose2DList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mstar::Pose2DList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mstar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mstar': ['/home/puneet/foxconnmultiagent/catkin_ws/src/mstar/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mstar::Pose2DList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mstar::Pose2DList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mstar::Pose2DList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mstar::Pose2DList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mstar::Pose2DList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mstar::Pose2DList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mstar::Pose2DList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e69772910d4436923e40502b8e6c939";
  }

  static const char* value(const ::mstar::Pose2DList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e69772910d44369ULL;
  static const uint64_t static_value2 = 0x23e40502b8e6c939ULL;
};

template<class ContainerAllocator>
struct DataType< ::mstar::Pose2DList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mstar/Pose2DList";
  }

  static const char* value(const ::mstar::Pose2DList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mstar::Pose2DList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Pose2D[] poses\n\
================================================================================\n\
MSG: mstar/Pose2D\n\
float32 x\n\
float32 y\n\
float32 yaw\n\
";
  }

  static const char* value(const ::mstar::Pose2DList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mstar::Pose2DList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose2DList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mstar::Pose2DList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mstar::Pose2DList_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mstar::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSTAR_MESSAGE_POSE2DLIST_H
