// Generated by gencpp from file mstar/PriorityPlan.msg
// DO NOT EDIT!


#ifndef MSTAR_MESSAGE_PRIORITYPLAN_H
#define MSTAR_MESSAGE_PRIORITYPLAN_H

#include <ros/service_traits.h>


#include <mstar/PriorityPlanRequest.h>
#include <mstar/PriorityPlanResponse.h>


namespace mstar
{

struct PriorityPlan
{

typedef PriorityPlanRequest Request;
typedef PriorityPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PriorityPlan
} // namespace mstar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mstar::PriorityPlan > {
  static const char* value()
  {
    return "fd5a9e5a4e9db09f05592023da0f0f50";
  }

  static const char* value(const ::mstar::PriorityPlan&) { return value(); }
};

template<>
struct DataType< ::mstar::PriorityPlan > {
  static const char* value()
  {
    return "mstar/PriorityPlan";
  }

  static const char* value(const ::mstar::PriorityPlan&) { return value(); }
};


// service_traits::MD5Sum< ::mstar::PriorityPlanRequest> should match 
// service_traits::MD5Sum< ::mstar::PriorityPlan > 
template<>
struct MD5Sum< ::mstar::PriorityPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mstar::PriorityPlan >::value();
  }
  static const char* value(const ::mstar::PriorityPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mstar::PriorityPlanRequest> should match 
// service_traits::DataType< ::mstar::PriorityPlan > 
template<>
struct DataType< ::mstar::PriorityPlanRequest>
{
  static const char* value()
  {
    return DataType< ::mstar::PriorityPlan >::value();
  }
  static const char* value(const ::mstar::PriorityPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mstar::PriorityPlanResponse> should match 
// service_traits::MD5Sum< ::mstar::PriorityPlan > 
template<>
struct MD5Sum< ::mstar::PriorityPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mstar::PriorityPlan >::value();
  }
  static const char* value(const ::mstar::PriorityPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mstar::PriorityPlanResponse> should match 
// service_traits::DataType< ::mstar::PriorityPlan > 
template<>
struct DataType< ::mstar::PriorityPlanResponse>
{
  static const char* value()
  {
    return DataType< ::mstar::PriorityPlan >::value();
  }
  static const char* value(const ::mstar::PriorityPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSTAR_MESSAGE_PRIORITYPLAN_H
