// Generated by gencpp from file mstar/PriorityPlanResponse.msg
// DO NOT EDIT!


#ifndef MSTAR_MESSAGE_PRIORITYPLANRESPONSE_H
#define MSTAR_MESSAGE_PRIORITYPLANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mstar/Belief.h>

namespace mstar
{
template <class ContainerAllocator>
struct PriorityPlanResponse_
{
  typedef PriorityPlanResponse_<ContainerAllocator> Type;

  PriorityPlanResponse_()
    : path()  {
    }
  PriorityPlanResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mstar::Belief_<ContainerAllocator>  _path_type;
  _path_type path;




  typedef boost::shared_ptr< ::mstar::PriorityPlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mstar::PriorityPlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PriorityPlanResponse_

typedef ::mstar::PriorityPlanResponse_<std::allocator<void> > PriorityPlanResponse;

typedef boost::shared_ptr< ::mstar::PriorityPlanResponse > PriorityPlanResponsePtr;
typedef boost::shared_ptr< ::mstar::PriorityPlanResponse const> PriorityPlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mstar::PriorityPlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mstar::PriorityPlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mstar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mstar': ['/home/puneet/foxconnmultiagent/catkin_ws/src/mstar/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mstar::PriorityPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mstar::PriorityPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mstar::PriorityPlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mstar::PriorityPlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mstar::PriorityPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mstar::PriorityPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mstar::PriorityPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a96641c84d3cf8054253ee45def8662";
  }

  static const char* value(const ::mstar::PriorityPlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a96641c84d3cf80ULL;
  static const uint64_t static_value2 = 0x54253ee45def8662ULL;
};

template<class ContainerAllocator>
struct DataType< ::mstar::PriorityPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mstar/PriorityPlanResponse";
  }

  static const char* value(const ::mstar::PriorityPlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mstar::PriorityPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Belief path\n\
\n\
\n\
================================================================================\n\
MSG: mstar/Belief\n\
Path2D[] belief\n\
\n\
================================================================================\n\
MSG: mstar/Path2D\n\
int8 id\n\
int32 timestamp\n\
Pose2D[] poses\n\
\n\
================================================================================\n\
MSG: mstar/Pose2D\n\
float32 x\n\
float32 y\n\
float32 yaw\n\
";
  }

  static const char* value(const ::mstar::PriorityPlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mstar::PriorityPlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PriorityPlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mstar::PriorityPlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mstar::PriorityPlanResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    s << std::endl;
    Printer< ::mstar::Belief_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSTAR_MESSAGE_PRIORITYPLANRESPONSE_H
