// Generated by gencpp from file mstar/PriorityPlanRequest.msg
// DO NOT EDIT!


#ifndef MSTAR_MESSAGE_PRIORITYPLANREQUEST_H
#define MSTAR_MESSAGE_PRIORITYPLANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mstar/Belief.h>
#include <mstar/Pose2DList.h>
#include <mstar/Pose2DList.h>

namespace mstar
{
template <class ContainerAllocator>
struct PriorityPlanRequest_
{
  typedef PriorityPlanRequest_<ContainerAllocator> Type;

  PriorityPlanRequest_()
    : robotIDs()
    , fix_paths()
    , current()
    , target()  {
    }
  PriorityPlanRequest_(const ContainerAllocator& _alloc)
    : robotIDs(_alloc)
    , fix_paths(_alloc)
    , current(_alloc)
    , target(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _robotIDs_type;
  _robotIDs_type robotIDs;

   typedef  ::mstar::Belief_<ContainerAllocator>  _fix_paths_type;
  _fix_paths_type fix_paths;

   typedef  ::mstar::Pose2DList_<ContainerAllocator>  _current_type;
  _current_type current;

   typedef  ::mstar::Pose2DList_<ContainerAllocator>  _target_type;
  _target_type target;




  typedef boost::shared_ptr< ::mstar::PriorityPlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mstar::PriorityPlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PriorityPlanRequest_

typedef ::mstar::PriorityPlanRequest_<std::allocator<void> > PriorityPlanRequest;

typedef boost::shared_ptr< ::mstar::PriorityPlanRequest > PriorityPlanRequestPtr;
typedef boost::shared_ptr< ::mstar::PriorityPlanRequest const> PriorityPlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mstar::PriorityPlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mstar::PriorityPlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mstar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mstar': ['/home/puneet/foxconnmultiagent/catkin_ws/src/mstar/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mstar::PriorityPlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mstar::PriorityPlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mstar::PriorityPlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mstar::PriorityPlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mstar::PriorityPlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mstar::PriorityPlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mstar::PriorityPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f771a356ef9828da23ebce50ee5073b3";
  }

  static const char* value(const ::mstar::PriorityPlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf771a356ef9828daULL;
  static const uint64_t static_value2 = 0x23ebce50ee5073b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mstar::PriorityPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mstar/PriorityPlanRequest";
  }

  static const char* value(const ::mstar::PriorityPlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mstar::PriorityPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] robotIDs\n\
Belief fix_paths\n\
Pose2DList current\n\
Pose2DList target\n\
\n\
================================================================================\n\
MSG: mstar/Belief\n\
Path2D[] belief\n\
\n\
================================================================================\n\
MSG: mstar/Path2D\n\
int8 id\n\
int32 timestamp\n\
Pose2D[] poses\n\
\n\
================================================================================\n\
MSG: mstar/Pose2D\n\
float32 x\n\
float32 y\n\
float32 yaw\n\
\n\
================================================================================\n\
MSG: mstar/Pose2DList\n\
Pose2D[] poses\n\
";
  }

  static const char* value(const ::mstar::PriorityPlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mstar::PriorityPlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robotIDs);
      stream.next(m.fix_paths);
      stream.next(m.current);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PriorityPlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mstar::PriorityPlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mstar::PriorityPlanRequest_<ContainerAllocator>& v)
  {
    s << indent << "robotIDs[]" << std::endl;
    for (size_t i = 0; i < v.robotIDs.size(); ++i)
    {
      s << indent << "  robotIDs[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.robotIDs[i]);
    }
    s << indent << "fix_paths: ";
    s << std::endl;
    Printer< ::mstar::Belief_<ContainerAllocator> >::stream(s, indent + "  ", v.fix_paths);
    s << indent << "current: ";
    s << std::endl;
    Printer< ::mstar::Pose2DList_<ContainerAllocator> >::stream(s, indent + "  ", v.current);
    s << indent << "target: ";
    s << std::endl;
    Printer< ::mstar::Pose2DList_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSTAR_MESSAGE_PRIORITYPLANREQUEST_H
