// Generated by gencpp from file path_db/Path2D.msg
// DO NOT EDIT!


#ifndef PATH_DB_MESSAGE_PATH2D_H
#define PATH_DB_MESSAGE_PATH2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <path_db/Pose2D.h>

namespace path_db
{
template <class ContainerAllocator>
struct Path2D_
{
  typedef Path2D_<ContainerAllocator> Type;

  Path2D_()
    : id(0)
    , timestamp(0)
    , poses()  {
    }
  Path2D_(const ContainerAllocator& _alloc)
    : id(0)
    , timestamp(0)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef int32_t _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector< ::path_db::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::path_db::Pose2D_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;




  typedef boost::shared_ptr< ::path_db::Path2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_db::Path2D_<ContainerAllocator> const> ConstPtr;

}; // struct Path2D_

typedef ::path_db::Path2D_<std::allocator<void> > Path2D;

typedef boost::shared_ptr< ::path_db::Path2D > Path2DPtr;
typedef boost::shared_ptr< ::path_db::Path2D const> Path2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_db::Path2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_db::Path2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_db

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'path_db': ['/home/puneet/foxconnmultiagent/catkin_ws/src/path_db/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_db::Path2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_db::Path2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_db::Path2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_db::Path2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_db::Path2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_db::Path2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_db::Path2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30794f2563bb2475cd7dbbb749b5cb73";
  }

  static const char* value(const ::path_db::Path2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30794f2563bb2475ULL;
  static const uint64_t static_value2 = 0xcd7dbbb749b5cb73ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_db::Path2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_db/Path2D";
  }

  static const char* value(const ::path_db::Path2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_db::Path2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 id\n\
int32 timestamp\n\
Pose2D[] poses\n\
\n\
================================================================================\n\
MSG: path_db/Pose2D\n\
float32 x\n\
float32 y\n\
float32 yaw\n\
";
  }

  static const char* value(const ::path_db::Path2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_db::Path2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.timestamp);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_db::Path2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_db::Path2D_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "timestamp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::path_db::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_DB_MESSAGE_PATH2D_H
