// Generated by gencpp from file path_db/QueryDB.msg
// DO NOT EDIT!


#ifndef PATH_DB_MESSAGE_QUERYDB_H
#define PATH_DB_MESSAGE_QUERYDB_H

#include <ros/service_traits.h>


#include <path_db/QueryDBRequest.h>
#include <path_db/QueryDBResponse.h>


namespace path_db
{

struct QueryDB
{

typedef QueryDBRequest Request;
typedef QueryDBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryDB
} // namespace path_db


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_db::QueryDB > {
  static const char* value()
  {
    return "14d424e88a7c969764a42fa104686aa4";
  }

  static const char* value(const ::path_db::QueryDB&) { return value(); }
};

template<>
struct DataType< ::path_db::QueryDB > {
  static const char* value()
  {
    return "path_db/QueryDB";
  }

  static const char* value(const ::path_db::QueryDB&) { return value(); }
};


// service_traits::MD5Sum< ::path_db::QueryDBRequest> should match 
// service_traits::MD5Sum< ::path_db::QueryDB > 
template<>
struct MD5Sum< ::path_db::QueryDBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_db::QueryDB >::value();
  }
  static const char* value(const ::path_db::QueryDBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_db::QueryDBRequest> should match 
// service_traits::DataType< ::path_db::QueryDB > 
template<>
struct DataType< ::path_db::QueryDBRequest>
{
  static const char* value()
  {
    return DataType< ::path_db::QueryDB >::value();
  }
  static const char* value(const ::path_db::QueryDBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_db::QueryDBResponse> should match 
// service_traits::MD5Sum< ::path_db::QueryDB > 
template<>
struct MD5Sum< ::path_db::QueryDBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_db::QueryDB >::value();
  }
  static const char* value(const ::path_db::QueryDBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_db::QueryDBResponse> should match 
// service_traits::DataType< ::path_db::QueryDB > 
template<>
struct DataType< ::path_db::QueryDBResponse>
{
  static const char* value()
  {
    return DataType< ::path_db::QueryDB >::value();
  }
  static const char* value(const ::path_db::QueryDBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_DB_MESSAGE_QUERYDB_H
