// Generated by gencpp from file control_node/PlannerRequest.msg
// DO NOT EDIT!


#ifndef CONTROL_NODE_MESSAGE_PLANNERREQUEST_H
#define CONTROL_NODE_MESSAGE_PLANNERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_node
{
template <class ContainerAllocator>
struct PlannerRequest_
{
  typedef PlannerRequest_<ContainerAllocator> Type;

  PlannerRequest_()
    : agents_ids()  {
    }
  PlannerRequest_(const ContainerAllocator& _alloc)
    : agents_ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _agents_ids_type;
  _agents_ids_type agents_ids;




  typedef boost::shared_ptr< ::control_node::PlannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_node::PlannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerRequest_

typedef ::control_node::PlannerRequest_<std::allocator<void> > PlannerRequest;

typedef boost::shared_ptr< ::control_node::PlannerRequest > PlannerRequestPtr;
typedef boost::shared_ptr< ::control_node::PlannerRequest const> PlannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_node::PlannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_node::PlannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'control_node': ['/home/puneet/foxconnmultiagent/catkin_ws/src/control_node/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_node::PlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_node::PlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_node::PlannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_node::PlannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_node::PlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_node::PlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_node::PlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36472c8231630bf6a33d23aebb667d5c";
  }

  static const char* value(const ::control_node::PlannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36472c8231630bf6ULL;
  static const uint64_t static_value2 = 0xa33d23aebb667d5cULL;
};

template<class ContainerAllocator>
struct DataType< ::control_node::PlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_node/PlannerRequest";
  }

  static const char* value(const ::control_node::PlannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_node::PlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] agents_ids\n\
";
  }

  static const char* value(const ::control_node::PlannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_node::PlannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agents_ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_node::PlannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_node::PlannerRequest_<ContainerAllocator>& v)
  {
    s << indent << "agents_ids[]" << std::endl;
    for (size_t i = 0; i < v.agents_ids.size(); ++i)
    {
      s << indent << "  agents_ids[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.agents_ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_NODE_MESSAGE_PLANNERREQUEST_H
