// Generated by gencpp from file control_node/Planner.msg
// DO NOT EDIT!


#ifndef CONTROL_NODE_MESSAGE_PLANNER_H
#define CONTROL_NODE_MESSAGE_PLANNER_H

#include <ros/service_traits.h>


#include <control_node/PlannerRequest.h>
#include <control_node/PlannerResponse.h>


namespace control_node
{

struct Planner
{

typedef PlannerRequest Request;
typedef PlannerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Planner
} // namespace control_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::control_node::Planner > {
  static const char* value()
  {
    return "07991e894479aa925d322b73f927b3b5";
  }

  static const char* value(const ::control_node::Planner&) { return value(); }
};

template<>
struct DataType< ::control_node::Planner > {
  static const char* value()
  {
    return "control_node/Planner";
  }

  static const char* value(const ::control_node::Planner&) { return value(); }
};


// service_traits::MD5Sum< ::control_node::PlannerRequest> should match 
// service_traits::MD5Sum< ::control_node::Planner > 
template<>
struct MD5Sum< ::control_node::PlannerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::control_node::Planner >::value();
  }
  static const char* value(const ::control_node::PlannerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_node::PlannerRequest> should match 
// service_traits::DataType< ::control_node::Planner > 
template<>
struct DataType< ::control_node::PlannerRequest>
{
  static const char* value()
  {
    return DataType< ::control_node::Planner >::value();
  }
  static const char* value(const ::control_node::PlannerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::control_node::PlannerResponse> should match 
// service_traits::MD5Sum< ::control_node::Planner > 
template<>
struct MD5Sum< ::control_node::PlannerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::control_node::Planner >::value();
  }
  static const char* value(const ::control_node::PlannerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_node::PlannerResponse> should match 
// service_traits::DataType< ::control_node::Planner > 
template<>
struct DataType< ::control_node::PlannerResponse>
{
  static const char* value()
  {
    return DataType< ::control_node::Planner >::value();
  }
  static const char* value(const ::control_node::PlannerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROL_NODE_MESSAGE_PLANNER_H
