// Generated by gencpp from file control_node/QueryDB.msg
// DO NOT EDIT!


#ifndef CONTROL_NODE_MESSAGE_QUERYDB_H
#define CONTROL_NODE_MESSAGE_QUERYDB_H

#include <ros/service_traits.h>


#include <control_node/QueryDBRequest.h>
#include <control_node/QueryDBResponse.h>


namespace control_node
{

struct QueryDB
{

typedef QueryDBRequest Request;
typedef QueryDBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryDB
} // namespace control_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::control_node::QueryDB > {
  static const char* value()
  {
    return "14d424e88a7c969764a42fa104686aa4";
  }

  static const char* value(const ::control_node::QueryDB&) { return value(); }
};

template<>
struct DataType< ::control_node::QueryDB > {
  static const char* value()
  {
    return "control_node/QueryDB";
  }

  static const char* value(const ::control_node::QueryDB&) { return value(); }
};


// service_traits::MD5Sum< ::control_node::QueryDBRequest> should match 
// service_traits::MD5Sum< ::control_node::QueryDB > 
template<>
struct MD5Sum< ::control_node::QueryDBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::control_node::QueryDB >::value();
  }
  static const char* value(const ::control_node::QueryDBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_node::QueryDBRequest> should match 
// service_traits::DataType< ::control_node::QueryDB > 
template<>
struct DataType< ::control_node::QueryDBRequest>
{
  static const char* value()
  {
    return DataType< ::control_node::QueryDB >::value();
  }
  static const char* value(const ::control_node::QueryDBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::control_node::QueryDBResponse> should match 
// service_traits::MD5Sum< ::control_node::QueryDB > 
template<>
struct MD5Sum< ::control_node::QueryDBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::control_node::QueryDB >::value();
  }
  static const char* value(const ::control_node::QueryDBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_node::QueryDBResponse> should match 
// service_traits::DataType< ::control_node::QueryDB > 
template<>
struct DataType< ::control_node::QueryDBResponse>
{
  static const char* value()
  {
    return DataType< ::control_node::QueryDB >::value();
  }
  static const char* value(const ::control_node::QueryDBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROL_NODE_MESSAGE_QUERYDB_H
